In [1]:
import numpy as np
from sklearn.datasets import load_iris
from random import random
import math
import operator

df = load_iris()
df.data.shape


(150, 4)

In [4]:
def divide_data(x):
    for i in df.data:
        if random() < x:
            train_data.append(i)
        else:
            test_data.append(i)


In [5]:
def feature_erase(k): #не использует его, потому что это бесполезно. Я все еще рассчитываю и переписываю стоимость
    for i in test_data:
        i[k] = None


In [6]:
def distance(x, y):#Евклидово расстояние
    dist = 0
    for i in range(x.shape[0]):
        dist += math.pow(x[i] - y[i], 2)
    return math.sqrt(dist)


In [9]:
def mean_sum(arr): #средняя сумма для вычисления значения после выбора k ближайших соседей
    sum_ = 0
    for i in arr:
           sum_+=i[feature_val]
    return sum_/len(arr)


In [10]:
def predict(arr, k):
    dist_arr = []
    for i in train_data:
        dist_arr.append((i, distance(i, arr))) #словарь для временного хранения объекта и расстояния до него
    dist_arr.sort(key=operator.itemgetter(1))
    nn = [] #массив ближайших соседей
    for j in range(k):
        nn.append(dist_arr[j][0]) 
    arr[feature_val] = mean_sum(nn) #переписать расчетное значение 
    print(arr)

In [11]:
train_data = []
test_data = []
feature_val = 0
divide_data(0.90)
#feature_erase(0)
print("first row - real data, second is predicted. By default predicts 1 feature of an object")
for i in test_data:
    print(i)
    predict(i, 7)
    print("----------")

first row - real data, second is predicted. By default predicts 1 feature of an object
[5.4 3.9 1.7 0.4]
[5.25714286 3.9        1.7        0.4       ]
----------
[5.4 3.7 1.5 0.2]
[5.27142857 3.7        1.5        0.2       ]
----------
[4.8 3.  1.4 0.1]
[4.84285714 3.         1.4        0.1       ]
----------
[5.1 3.5 1.4 0.3]
[5.08571429 3.5        1.4        0.3       ]
----------
[5.  3.  1.6 0.2]
[4.84285714 3.         1.6        0.2       ]
----------
[5.  3.4 1.6 0.4]
[5.01428571 3.4        1.6        0.4       ]
----------
[5.5 3.5 1.3 0.2]
[5.28571429 3.5        1.3        0.2       ]
----------
[4.6 3.2 1.4 0.2]
[4.6 3.2 1.4 0.2]
----------
[6.2 2.2 4.5 1.5]
[6.25714286 2.2        4.5        1.5       ]
----------
[5.7 2.6 3.5 1. ]
[5.65714286 2.6        3.5        1.        ]
----------
[6.  3.4 4.5 1.6]
[6.08571429 3.4        4.5        1.6       ]
----------
[5.7 2.8 4.1 1.3]
[5.71428571 2.8        4.1        1.3       ]
----------
[6.5 3.  5.8 2.2]
[6.62857143 3.         